/* SoC level DTS fixup file */

#define DT_FLASH_DEV_BASE_ADDRESS		FLASH_CTRL_0_BASE_ADDRESS
#define DT_FLASH_DEV_NAME			FLASH_CTRL_0_LABEL
#define DT_FLASH_CTRL_CLOCK_CONTROLLER		FLASH_CTRL_0_CLOCK_CONTROLLER
#define DT_FLASH_CTRL_CLOCK_NAME		FLASH_CTRL_0_CLOCK_NAME

